import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "plyr/dist/plyr.css";
import { AntdThemeProvider } from "EduSmart/components/Themes/AntdThemeProvider";
import { ThemeProvider } from "EduSmart/Provider/ThemeProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ChartThemeProvider } from "EduSmart/Provider/ChartThemeProvider";
import { NotificationProvider } from "EduSmart/Provider/NotificationProvider";
import "@ant-design/v5-patch-for-react-19";
// import Head from "next/head";
import GoogleProvider from "EduSmart/Provider/GoogleProvider";
import ClientBoot from "./video/ClientBoot";
import TitleMarquee from "EduSmart/components/BaseControl/TitleMarquee/TitleMarquee";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://www.edusmart.pro.vn"),
  title: {
    default: "EduSmart – Học cùng AI cho học sinh",
    template: "%s | EduSmart",
  },
  description:
    "Học thông minh cùng AI: gợi ý khóa học phù hợp, theo dõi tiến độ và bài kiểm tra cá nhân hoá trên EduSmart.",
  alternates: { canonical: "/" },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  openGraph: {
    type: "website",
    locale: "vi_VN",
    url: "/",
    title: "EduSmart",
    description: "EduSmart – Nơi chăm sóc tinh thần của bạn",
    siteName: "EduSmart",
    images: [
      {
        url: "https://www.edusmart.pro.vn/Logo.png",
        width: 1200,
        height: 630,
        alt: "EduSmart logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "EduSmart",
    description: "Generated by create next app",
    images: ["https://www.edusmart.pro.vn/Logo.png"],
  },
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/Logo.png",
        href: "/Logo.png",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/Logo.png",
        href: "/Logo.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head>
        <link rel="preconnect" href="https://api.EduSmart.vn" />
        <link rel="dns-prefetch" href="https://api.EduSmart.vn" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preload" as="style" href="/_next/static/css/xxx.css" />
        <link rel="preload" as="image" href="/emo.png" />
        <link rel="preload" as="image" href="/hero-bg.jpg" />
      </Head> */}
      <head>
        <meta name="robots" content="index,follow" />
        <meta
          name="google-site-verification"
          content="zHUQms0K0yncnzbqCtw9XTpot7mSQqw2npsCYfi8S84"
        />
        {process.env.NEXT_PUBLIC_API_URL && (
          <>
            <link rel="preconnect" href={process.env.NEXT_PUBLIC_API_URL} />
            <link rel="dns-prefetch" href={process.env.NEXT_PUBLIC_API_URL} />
          </>
        )}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        {/* ✅ BỎ dòng preload CSS hardcode vì không ổn định giữa các build */}
        {/* <link rel="preload" as="style" href="/_next/static/css/xxx.css" /> */}
        <link rel="preload" as="image" href="/Logo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientBoot />
        <TitleMarquee />
        <AntdRegistry>
          <ThemeProvider>
            <AntdThemeProvider>
              <ChartThemeProvider>
                <NotificationProvider>
                  <GoogleProvider>{children}</GoogleProvider>
                </NotificationProvider>
              </ChartThemeProvider>
            </AntdThemeProvider>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
