import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "plyr/dist/plyr.css";
import { AntdThemeProvider } from "EduSmart/components/Themes/AntdThemeProvider";
import { ThemeProvider } from "EduSmart/Provider/ThemeProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ChartThemeProvider } from "EduSmart/Provider/ChartThemeProvider";
import { NotificationProvider } from "EduSmart/Provider/NotificationProvider";
import "@ant-design/v5-patch-for-react-19";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://EduSmart-frontend.vercel.app"),
  title: { default: "EduSmart", template: "%s | EduSmart" },
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    locale: "vi_VN",
    url: "/",
    title: "EduSmart",
    description: "EmosEase – Nơi chăm sóc tinh thần của bạn",
    siteName: "EduSmart",
    images: [
      {
        url: "https://EduSmart-frontend.vercel.app/emo.png",
        width: 1200,
        height: 630,
        alt: "EduSmart logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "EduSmart",
    description: "Generated by create next app",
    images: ["https://EduSmart-frontend.vercel.app/emo.png"],
  },
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/emo.png",
        href: "/emo.png",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/emo.png",
        href: "/emo.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://api.EduSmart.vn" />
        <link rel="dns-prefetch" href="https://api.EduSmart.vn" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preload" as="style" href="/_next/static/css/xxx.css" />
        <link rel="preload" as="image" href="/emo.png" />
        <link rel="preload" as="image" href="/hero-bg.jpg" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <ThemeProvider>
            <AntdThemeProvider>
              <ChartThemeProvider>
                <NotificationProvider>{children}</NotificationProvider>
              </ChartThemeProvider>
            </AntdThemeProvider>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
